"""
en_complex3.py

Generates E(n), the subcomplex of ZP(n) consisting of all top facets with
only even-labeled vertices, and decomposes it as:

    E(n) = st(0) ? EB(n)

where:
    st(0)  = star of vertex 0 in E(n):
             all faces of E(n) facets containing 0,
             including faces that do not themselves contain 0.
    EB(n)  = subcomplex of E(n) generated by all vertices EXCEPT 0:
             all simplices of E(n) that do not involve vertex 0.
             This is NOT simply the set of E(n) facets with 0 deleted;
             it includes all faces of ALL E(n) facets that happen not
             to contain 0.

Their intersection st(0) ? EB(n) is also computed.

E(n) has exactly n facets of size n-2 (one per gap vertex v):
    gap v: {2*((v+1+k) % n) : k = 0, ..., n-3}

Usage:
    python3 en_complex3.py <n>

Output:
    en3_n<n>_facets.txt  ? all n facets of E(n)
    en3_n<n>_st0.txt     ? facets of st(0)
    en3_n<n>_ebn.txt     ? facets of EB(n)
    en3_n<n>_inter.txt   ? facets of st(0) ? EB(n)
"""

import sys
import os
import time
from itertools import combinations
from collections import Counter


def get_en_facets(n):
    """Generate the n facets of E(n), each of size n-2."""
    facets = []
    for v in range(n):
        path_verts = [(v + 1 + k) % n for k in range(n - 1)]
        f = tuple(sorted(2 * path_verts[k] for k in range(n - 2)))
        facets.append(f)
    return sorted(facets)


def all_faces(facets):
    """All faces (including empty) of a list of facets."""
    faces = set()
    for f in facets:
        for r in range(len(f) + 1):
            for sub in combinations(f, r):
                faces.add(sub)
    return faces


def complex_facets(simplices):
    """Maximal non-empty simplices."""
    sl = sorted(simplices)
    return [s for s in sl if s and not any(set(s) < set(t) for t in sl)]


def intersect_complexes(facets_A, facets_B):
    """
    Facets of the intersection of two simplicial complexes given by their
    facets. Returns maximal elements of {a ? b : a in A, b in B}.
    """
    caps = set()
    for a in facets_A:
        a_set = set(a)
        for b in facets_B:
            cap = tuple(sorted(a_set & set(b)))
            if cap:
                caps.add(cap)
    if not caps:
        return []
    caps_list = sorted(caps, key=len, reverse=True)
    maximal = []
    for c in caps_list:
        if not any(set(c) < set(m) for m in maximal):
            maximal.append(c)
    return sorted(maximal)


def write_facets(facets, filepath):
    with open(filepath, 'w') as f:
        f.write(','.join(str(list(fac)) for fac in facets))
        f.write('\n')
    return len(facets)


def report(label, facets, filepath):
    count = write_facets(facets, filepath)
    kb = os.path.getsize(filepath) / 1024
    sizes = dict(sorted(Counter(len(f) for f in facets).items()))
    print(f"  {label}: {count} facets {sizes}  ->  '{filepath}'  ({kb:.1f} KB)")


def main():
    if len(sys.argv) > 1:
        try:
            n = int(sys.argv[1])
        except ValueError:
            print(f"Error: argument must be an integer, got '{sys.argv[1]}'")
            sys.exit(1)
    else:
        n = 8
        print(f"No n supplied; using default n=8.")
        print("Usage: python3 en_complex3.py <n>\n")

    if n < 4:
        print("Error: n must be >= 4"); sys.exit(1)

    t0 = time.time()
    facets = get_en_facets(n)
    print(f"Computing E({n}) decomposition: st(0) ? EB({n})")
    print(f"  E({n}): {n} facets of size {n-2}")
    print()

    # All simplices of E(n)
    all_simp = all_faces(facets)

    # st(0): all faces of facets containing vertex 0
    st0_simp = all_faces([f for f in facets if 0 in f])
    st0_facs = complex_facets(st0_simp)

    # EB(n): all simplices of E(n) not involving vertex 0
    ebn_simp = {s for s in all_simp if 0 not in s}
    ebn_facs = complex_facets(ebn_simp)

    # st(0) ? EB(n): simplices in both subcomplexes
    inter_facs = intersect_complexes(st0_facs, ebn_facs)

    report(f"E({n})",          facets,     f"en3_n{n}_facets.txt")
    report(f"st(0)",           st0_facs,   f"en3_n{n}_st0.txt")
    report(f"EB({n})",         ebn_facs,   f"en3_n{n}_ebn.txt")
    report(f"st(0) ? EB({n})", inter_facs, f"en3_n{n}_inter.txt")

    print(f"\n  Time: {time.time()-t0:.3f}s")


if __name__ == "__main__":
    main()